<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.5">
  <POU Name="MAIN" Id="{539be4ca-25cc-43dd-904f-f047e8f2e8d2}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	inta : INT;
	inz : int;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[inta := 10;
inz := 2;]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>